POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2Njg4ZTFlODA1ZmIzYmZkN2ExNWVjOWIiLCJpYXQiOjE3MjA3ODA3MTN9.xwJuXON84-nvfdrK9BEQIvQG_ECEFOkLozgU81kUkc4

{
  "title": "akun blogi",
  "author": "aku ankka",
  "url": "akunblogi.fi",
  "likes": "3"
}